### ISSUE TITLE
Auto Kick when using a command on someone on my server

### ISSUE THREAD

**Issue by InkaSoldier** [realSmushyTaco/Troll-Commands#1]
There is a weird bug with the mod that when I wanna troll someone on my server and put the comand for example: /rickroll "playername" he gets insta kicked from my server and it says there is an error with the command. Idk what could be happening

**Comment by chickendabest** [comment]
me too

**Comment by SmushyTaco** [comment]
Thanks for the report, I'll investigate soon, there's a huge heat wave where I am that I don't want to be working in. Sometime next week I'll probably fix it.

**Comment by SmushyTaco** [comment]
Fixed
